version: '2.1'

services:
  mysql:
    image: mysql:5.7
    container_name: timeline_db
    ports:
        - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --init-file="/deploy/init.sql"
    volumes:
      - /project/data/timeline_db:/var/lib/mysql
      - /project/deploy/init.sql:/deploy/init.sql
    environment:
        MYSQL_ROOT_PASSWORD: {MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: timeline
        MYSQL_USER: {MYSQL_USER}
        MYSQL_PASSWORD: {MYSQL_PASSWORD}
    restart: always
  timeline.me:
    image: timeline
    container_name: timeline_web
    build: .
    ports:
      - 8000:80
    volumes:
      - .:/app
    restart: always
    depends_on:
      - mysql

